using System;

namespace BLL.PropertyClasses.Transaction
{
    public class Invoice_EntryProperty
    {
        public Int64 Purchase_Master_ID { get; set; }
        public string Invoice_Date { get; set; }
        public string Financial_Year { get; set; }
        public string Invoice_No { get; set; }
        public Int64 From_Party { get; set; }
        public Int64 To_Party { get; set; }
        public string Bill_OF_Entry_Date { get; set; }
        public string Party_Invoice_No { get; set; }
        public string Payment_Mode { get; set; }
        public string Payment_Days { get; set; }
        public string Payment_Date { get; set; }
        public string Transaction_Date { get; set; }
        public Int64 From_Party_Code { get; set; }
        public Int64 BillTo_Party_Code { get; set; }
        public Int64 IS_Reverse { get; set; }
        public Int64 HSN_ID { get; set; }
        public Int64 ItemSaleReturnMasterID { get; set; }
        public Int64 ItemSaleReturnDtlID { get; set; }
        public Int64 ItemPurchaseMasterID { get; set; }
        public Int64 ItemPurchaseDetailID { get; set; }
        public Int64 ItemPurchaseRtnMasterID { get; set; }
        public Int64 ItemPurchaseReturnDtlID { get; set; }
        public Int64 ItemSaleDetailID { get; set; }
        public Int64 ItemSaleMasterID { get; set; }
        public double CGST { get; set; }
        public double SGST { get; set; }
        public double IGST { get; set; }
        public double CGST_Amt { get; set; }
        public double SGST_Amt { get; set; }
        public double IGST_Amt { get; set; }
        public double Total_Amt { get; set; }
        public double Gross_Amt { get; set; }
        public double Add_Amt { get; set; }
        public double Less_Amt { get; set; }
        public double Net_Amt { get; set; }
        public string Challan_No { get; set; }
        public string Fin_Year { get; set; }
        public string From_Date { get; set; }
        public string To_Date { get; set; }
        public Int64 SrNo { get; set; }
        public string Unit_Type { get; set; }
        public Int64 Item_Code { get; set; }
        public double Split_Per { get; set; }
        public string Type { get; set; }
        public Int64 Lot_ID { get; set; }
        public Int64 Parent_Lot_ID { get; set; }
        public Int64 Source_Code { get; set; }
        public Int64 Source_Company_Code { get; set; }
        public Int64 Article_Code { get; set; }
        public Int64 MSize_Code { get; set; }
        public Int64 Quality_Code { get; set; }
        public Int64 SubQuality_Code { get; set; }
        public double Quantity { get; set; }
        public double Rate_Dollar { get; set; }
        public double Rate_Local { get; set; }
        public double Rate_Purchase { get; set; }
        public double Prem_Disc { get; set; }
        public Int64 Terms { get; set; }
        public double Prem_Amount_Dollar { get; set; }
        public double Prem_Amount_Local { get; set; }
        public double Prem_Amount_Purchase { get; set; }
        public double Prem_Rate_Dollar { get; set; }
        public double Prem_Rate_Local { get; set; }
        public double Prem_Rate_Purchase { get; set; }
        public double Amount_Dollar { get; set; }
        public double Amount_Local { get; set; }
        public string Issue_Type { get; set; }
        public string Brokrage_Type { get; set; }
        public double Brokrage { get; set; }
        public double Brokrage_Amount_Dollar { get; set; }
        public double Brokrage_Amount_Local { get; set; }
        public double Brokrage_Amount_Purchase { get; set; }
        public string Create_Date { get; set; }
        public string Create_Time { get; set; }
        public double Balance_Quantity { get; set; }
        public double Balance_Carat { get; set; }
        public string Remark { get; set; }
        public Int64 Goods_Rec_Pcs { get; set; }
        public double Goods_Rec_Carat { get; set; }
        public string Goods_Rec_Date { get; set; }
        public string Goods_Rec_Time { get; set; }
        public Int64 Goods_Rec_Employee_Code { get; set; }
        public string Goods_Rec_Computer_IP { get; set; }
        public Int64 Loss_Pcs { get; set; }
        public Int64 Lost_Pcs { get; set; }
        public Int64 Trn_Id { get; set; }
        public Int64 IS_Approve { get; set; }
        public Int64 IS_Hold { get; set; }
        public double Vat_Per { get; set; }
        public double Add_Vat_Per { get; set; }
        public double Discount { get; set; }
        public double Add_Amount { get; set; }
        public double Less_Amount { get; set; }
        public double Net_Amount_Dollar { get; set; }
        public double Net_Amount_Local { get; set; }
        public double Net_Amount_Purchase { get; set; }
        public Int64 Company_Code { get; set; }
        public Int64 Branch_Code { get; set; }
        public decimal MTR { get; set; }
        public decimal Weight { get; set; }
        public decimal Rate { get; set; }
        public int Line { get; set; }
        public int Taka { get; set; }
        public decimal Cut { get; set; }
        public int Buta { get; set; }
        public int Buta_Rate { get; set; }
        public double Discount_Per { get; set; }
        public bool Is_Paid { get; set; }
        public Int64 Invoice_No_Checked { get; set; }
    }
}
